### ISSUE TITLE
.R extension forced to lower case

### ISSUE THREAD

**Issue by DimitriF** [blosloos/enviMass#4]
Hello,
I wanted to look at your shiny app but it seems that all the files extension are forced to lower case, so when the files are sourced, they cannot be found.
I tried to clone the repo,  `devtools::install_github`, `shiny::runGitHub`
I started to find and replace in the ui.R and server.R file but it seems that there is `source` everywhere...
Dimitri

**Comment by blosloos** [comment]
Hi Dimitri
Yes, there is a lot of sourcing in there; and its a lot of content, too. I am not sure if your really want to go through that. Concerning installation, have you checked www.envimass.ch? I haven't heard of any case where the .r or .R file extension has prevented sourcing after installation ...

**Comment by DimitriF** [comment]
Tested the installation from the link but nothing new compare to what I did.
I run from linux which is case sensitive at the opposite of windows (if my rapid googling is correct)

**Comment by DimitriF** [comment]
I just installed, run the app, and made the calculation on my data from a windows computer.
One mistake I said from before, there is no Rtools for linux so I skipped this step.
Do you have feedback from successful install on ubuntu ?

**Comment by blosloos** [comment]
no, noone used the package on ubuntu / linux so far ... but thanks for the feedback, Dimitri.

**Comment by DimitriF** [comment]
my pleasure, if you want to make it linux compatible and need a user or even help, I'll be happy to help.
I saw in the debug.log file a lot of windows stuff so it seems that file extension is not the only trouble.

**Comment by blosloos** [comment]
thanks!
